id: P63E4E98A
initial_creation_type: input
source_metadata:
  title: Vajrapāṇi Series
  language: en
  description: 'A series of texts related to the deity Vajrapāṇi (phyag na rdo rje),
    who embodies the power and strength of all the buddhas:'
  volume:
    4cf42ce7d1df45068810c5bf4047a0fd:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Dhāraṇī
    ed9313f98e17487baeafb54dd9751ebb:
      title: Daily Practice of Dorje Gotrab
      parent: Dorje Gotrab
created_at: '2022-03-01T06:31:26.901526'
last_modified_at: '2022-03-01T06:31:26.901532'
